# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Redware/System-Snake/snake_project.srcs/constrs_1/new/nexysddr_master.xdc

# IP: C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_pixel || ORIG_REF_NAME==clk_wiz_pixel}]
