# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Redware/System-Snake/snake_project/snake_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Redware/System-Snake/snake_project/snake_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet c:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.dcp
set_property used_in_implementation false [get_files c:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.dcp]
read_verilog {
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/snake_header.vh
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/random_header.vh
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/interface_header.vh
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/vga_controller_header.vh
}
read_ip -quiet C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.xci
set_property used_in_implementation false [get_files -all c:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel_ooc.xdc]
set_property is_locked true [get_files C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.xci]

read_verilog -library xil_defaultlib -sv {
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/random_source.sv
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/vga_controller_source.sv
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/top_module.sv
  C:/Users/Redware/System-Snake/snake_project.srcs/sources_1/new/snake_source.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/Redware/System-Snake/snake_project/snake_project.srcs/sources_1/imports/new/PS2Receiver.v
  C:/Users/Redware/System-Snake/snake_project/snake_project.srcs/sources_1/imports/new/debouncer.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Redware/System-Snake/snake_project.srcs/constrs_1/new/nexysddr_master.xdc
set_property used_in_implementation false [get_files C:/Users/Redware/System-Snake/snake_project.srcs/constrs_1/new/nexysddr_master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_module -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
